# Generated by Django 5.0.6 on 2024-07-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackTitan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('name', models.CharField(max_length=100)),
                ('status', models.TextField()),
                ('ability', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JujutsuKaisen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('name', models.CharField(max_length=100)),
                ('status', models.TextField()),
                ('ability', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('name', models.CharField(max_length=100)),
                ('status', models.TextField()),
                ('ability', models.CharField(max_length=100)),
            ],
        ),
    ]
